# Generated by Django 5.2.6 on 2025-09-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_weight', models.FloatField(blank=True, null=True)),
                ('new_weight', models.FloatField(blank=True, null=True)),
                ('prev_sets', models.IntegerField(blank=True, null=True)),
                ('new_sets', models.IntegerField(blank=True, null=True)),
                ('prev_reps', models.IntegerField(blank=True, null=True)),
                ('new_reps', models.IntegerField(blank=True, null=True)),
                ('prev_rpe', models.FloatField(blank=True, null=True)),
                ('new_rpe', models.FloatField(blank=True, null=True)),
                ('applied_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_scope', models.CharField(choices=[('EXERCISE', 'Exercise'), ('SESSION', 'Session'), ('BLOCK', 'Block')], default='EXERCISE', max_length=20)),
                ('suggested_weight', models.FloatField(blank=True, null=True)),
                ('suggested_sets', models.IntegerField(blank=True, null=True)),
                ('suggested_reps', models.IntegerField(blank=True, null=True)),
                ('suggested_rpe', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
