# Generated by Django 5.2.6 on 2025-09-08 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiadjustmentlog',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiadjustmentlog',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_adjustments', to='training.exercise'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_ai_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='training.trainingblock'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='training.exercise'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='training.trainingsession'),
        ),
        migrations.AddField(
            model_name='aiadjustmentlog',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aisuggestion'),
        ),
    ]
