# Generated by Django 5.2.6 on 2025-09-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachathlete',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
